services:
  # A static site
  - type: web
    name: evently
    runtime: static
    buildCommand: yarn; yarn build
    staticPublishPath: ./out
    pullRequestPreviewsEnabled: true # Enable service previews
    buildFilter:
      paths:
        - src/**/*.js
      ignoredPaths:
        - src/**/*.test.js
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: redirect
        source: /old
        destination: /new
      - type: rewrite
        source: /a/*
        destination: /a
